import 'package:cloud_firestore/cloud_firestore.dart';

/// Structured product details generated by AI from the product image.
/// All fields are optional — old products without AI generation will have nulls,
/// which the UI handles gracefully by falling back to [description].
class ProductDetails {
  final String? tagline;
  final String? narrative;
  final String? material;
  final String? craft;
  final String? color;
  final String? dimensions;
  final String? occasion;
  final String? care;

  const ProductDetails({
    this.tagline,
    this.narrative,
    this.material,
    this.craft,
    this.color,
    this.dimensions,
    this.occasion,
    this.care,
  });

  bool get isEmpty =>
      tagline == null &&
      narrative == null &&
      material == null &&
      craft == null &&
      color == null &&
      dimensions == null &&
      occasion == null &&
      care == null;

  factory ProductDetails.fromMap(Map<String, dynamic> map) {
    return ProductDetails(
      tagline: map['tagline'] as String?,
      narrative: map['narrative'] as String?,
      material: map['material'] as String?,
      craft: map['craft'] as String?,
      color: map['color'] as String?,
      dimensions: map['dimensions'] as String?,
      occasion: map['occasion'] as String?,
      care: map['care'] as String?,
    );
  }

  Map<String, dynamic> toMap() => {
        if (tagline != null) 'tagline': tagline,
        if (narrative != null) 'narrative': narrative,
        if (material != null) 'material': material,
        if (craft != null) 'craft': craft,
        if (color != null) 'color': color,
        if (dimensions != null) 'dimensions': dimensions,
        if (occasion != null) 'occasion': occasion,
        if (care != null) 'care': care,
      };
}

class ProductModel {
  final String id;
  final String name;
  final String description;
  final String image;
  final double price;
  final int stock;
  final String categoryId;
  final Timestamp createdAt;
  final ProductDetails? details;

  ProductModel({
    required this.id,
    required this.name,
    required this.description,
    required this.image,
    required this.price,
    required this.stock,
    required this.categoryId,
    required this.createdAt,
    this.details,
  });

  factory ProductModel.fromMap(
    String id,
    Map<String, dynamic> data,
  ) {
    return ProductModel(
      id: id,
      name: data['name'] ?? '',
      description: data['description'] ?? '',
      image: data['image'] ?? '',
      price: (data['price'] ?? 0).toDouble(),
      stock: data['stock'] ?? 0,
      categoryId: data['categoryId'] ?? '',
      createdAt: data['createdAt'] ?? Timestamp.now(),
      details: data['details'] != null
          ? ProductDetails.fromMap(
              Map<String, dynamic>.from(data['details'] as Map),
            )
          : null,
    );
  }
}
